// =============================================
// APROBADOS YA — Estructura de Datos
// =============================================

// =================== PERMISOS ===================

const PERMITS = [
  { id: 'B',    name: 'Permiso B',                     icon: '🚗', desc: 'Turismos y furgonetas hasta 3.500 kg' },
  { id: 'A',    name: 'Permiso A1/A2',                 icon: '🏍️', desc: 'Motocicletas' },
  { id: 'AM',   name: 'Permiso AM',                    icon: '🛵', desc: 'Ciclomotores de dos y tres ruedas' },
  { id: 'C',    name: 'Permiso C1/C',                  icon: '🚛', desc: 'Camiones y vehículos de más de 3.500 kg' },
  { id: 'D',    name: 'Permiso D1/D',                  icon: '🚌', desc: 'Autobuses y vehículos de más de 9 plazas' },
  { id: 'BE',   name: 'Permiso B+E',                   icon: '🚐', desc: 'Turismos con remolque ligero' },
  { id: 'CE',   name: 'Permiso C+E',                   icon: '🚚', desc: 'Camiones con semirremolque' },
  { id: 'ADR',  name: 'ADR',                            icon: '☢️', desc: 'Mercancías peligrosas por carretera' },
  { id: 'CAP_M',name: 'CAP Mercancías',                icon: '📦', desc: 'Certificado de aptitud profesional' },
  { id: 'CAP_V',name: 'CAP Viajeros',                  icon: '🧳', desc: 'Certificado de aptitud profesional' },
  { id: 'CP_M', name: 'Comp. Profesional Mercancías',  icon: '🏭', desc: 'Cualificación inicial' },
  { id: 'CP_V', name: 'Comp. Profesional Viajeros',    icon: '👥', desc: 'Cualificación inicial' },
  { id: 'CS',   name: 'Consejero de Seguridad',        icon: '🛡️', desc: 'Transporte de mercancías peligrosas' },
  { id: 'RP',   name: 'Recuperación de Puntos',        icon: '⭐', desc: 'Curso de sensibilización y reeducación vial' },
];

// =================== TEMAS POR PERMISO ===================

const PERMIT_TOPICS = {
  'B': [
    { id: 'senales',        name: 'Señales de Tráfico',           icon: '🚦', numTests: 100 },
    { id: 'normas',         name: 'Normas de Circulación',        icon: '📋', numTests: 100 },
    { id: 'prioridad',      name: 'Prioridad de Paso',            icon: '🔄', numTests: 100 },
    { id: 'velocidad',      name: 'Velocidad y Distancias',       icon: '⚡', numTests: 100 },
    { id: 'adelantamiento', name: 'Adelantamiento',               icon: '🏎️', numTests: 100 },
    { id: 'alcohol',        name: 'Alcohol, Drogas y Fármacos',  icon: '🍺', numTests: 100 },
    { id: 'mecanica',       name: 'Mecánica y Seguridad',         icon: '🔧', numTests: 100 },
    { id: 'iluminacion',    name: 'Iluminación',                  icon: '💡', numTests: 100 },
    { id: 'medioambiente',  name: 'Conducción Eficiente',         icon: '🌿', numTests: 100 },
    { id: 'accidentes',     name: 'Accidentes y Primeros Auxilios', icon: '🚑', numTests: 100 },
  ],
  'A': [
    { id: 'normas_moto',    name: 'Normas de Circulación',        icon: '📋', numTests: 100 },
    { id: 'senales_moto',   name: 'Señales de Tráfico',           icon: '🚦', numTests: 100 },
    { id: 'mecanica_moto',  name: 'Mecánica de Motocicletas',     icon: '🔧', numTests: 100 },
    { id: 'seguridad_moto', name: 'Seguridad Activa y Pasiva',    icon: '🛡️', numTests: 100 },
  ],
  'AM': [
    { id: 'normas_am',      name: 'Normas de Circulación',        icon: '📋', numTests: 100 },
    { id: 'senales_am',     name: 'Señales de Tráfico',           icon: '🚦', numTests: 100 },
    { id: 'mecanica_am',    name: 'Mecánica del Ciclomotor',      icon: '🔧', numTests: 100 },
  ],
  'C': [
    { id: 'normas_c',       name: 'Normas de Circulación',        icon: '📋', numTests: 100 },
    { id: 'mecanica_c',     name: 'Mecánica de Camiones',         icon: '🔧', numTests: 100 },
    { id: 'carga',          name: 'Carga y Transporte',           icon: '📦', numTests: 100 },
    { id: 'conduccion_c',   name: 'Conducción Eficiente',         icon: '🌿', numTests: 100 },
  ],
  'D': [
    { id: 'normas_d',       name: 'Normas de Circulación',        icon: '📋', numTests: 100 },
    { id: 'viajeros',       name: 'Transporte de Viajeros',       icon: '👥', numTests: 100 },
    { id: 'mecanica_d',     name: 'Mecánica de Autobuses',        icon: '🔧', numTests: 100 },
  ],
  'BE':  [{ id: 'remolque_b',  name: 'Remolque Ligero B+E',          icon: '🚐', numTests: 100 }],
  'CE':  [{ id: 'remolque_c',  name: 'Semirremolque C+E',             icon: '🚚', numTests: 100 }],
  'ADR': [
    { id: 'adr_gral',       name: 'Disposiciones Generales',      icon: '📋', numTests: 100 },
    { id: 'adr_clases',     name: 'Clases de Mercancías',         icon: '☢️', numTests: 100 },
    { id: 'adr_vehiculos',  name: 'Vehículos y Equipos',          icon: '🚛', numTests: 100 },
  ],
  'CAP_M': [{ id: 'cap_m_general', name: 'CAP Mercancías — General', icon: '📦', numTests: 100 }],
  'CAP_V': [{ id: 'cap_v_general', name: 'CAP Viajeros — General',   icon: '🧳', numTests: 100 }],
  'CP_M':  [{ id: 'cp_m_general',  name: 'Comp. Prof. Mercancías',   icon: '🏭', numTests: 100 }],
  'CP_V':  [{ id: 'cp_v_general',  name: 'Comp. Prof. Viajeros',     icon: '👥', numTests: 100 }],
  'CS':    [{ id: 'cs_general',    name: 'Consejero de Seguridad',   icon: '🛡️', numTests: 100 }],
  'RP':    [{ id: 'rp_general',    name: 'Recuperación de Puntos',   icon: '⭐', numTests: 100 }],
};

// =================== BANCO DE PREGUNTAS (DEMO) ===================
// Estructura: QBANK[permitId][temaId] = array de preguntas
// Cada pregunta: { id, q, options:[A,B,C,D], correct(0-3), explanation, image }
// El Test N usará las preguntas de los índices [(N-1)*30 .. N*30]

const QBANK = {
  'B': {
    'senales': [
      { id:'S01', q:'¿Qué forma tienen las señales de prohibición?', options:['Triangulares con borde rojo','Circulares con borde rojo y fondo blanco','Cuadradas con fondo azul','Octogonales rojas'], correct:1, explanation:'Las señales de prohibición son circulares con borde rojo y fondo blanco. Excepción: STOP es octogonal y CEDA EL PASO es triangular invertido.' },
      { id:'S02', q:'¿Qué forma tienen las señales de advertencia de peligro?', options:['Circulares con borde rojo','Triangulares con borde rojo y fondo blanco o amarillo','Cuadradas con fondo azul','Rectangulares con fondo verde'], correct:1, explanation:'Las señales de peligro son triangulares con borde rojo y fondo blanco o amarillo, con el vértice hacia arriba.' },
      { id:'S03', q:'¿Qué color tienen las señales de indicación en autopistas españolas?', options:['Verde','Azul','Blanco','Amarillo'], correct:1, explanation:'En autopistas y autovías las señales de indicación tienen fondo azul. En carreteras convencionales el fondo es verde.' },
      { id:'S04', q:'¿Qué significan las señales circulares con fondo azul y símbolo blanco?', options:['Prohibición','Peligro','Obligación','Información'], correct:2, explanation:'Las señales circulares de fondo azul con símbolo blanco son señales de OBLIGACIÓN. Indican lo que el conductor debe hacer.' },
      { id:'S05', q:'Cuando un agente de tráfico contradice un semáforo, ¿qué debes obedecer?', options:['El semáforo siempre tiene prioridad','Al agente de tráfico, tiene prioridad sobre cualquier señal','La señal más restrictiva','Ninguna de las dos, detenerse'], correct:1, explanation:'Los agentes de tráfico tienen autoridad sobre cualquier señal de tráfico, incluidos los semáforos. Sus indicaciones prevalecen siempre.' },
      { id:'S06', q:'¿Qué indica un triángulo con signo de exclamación (!)?', options:['Paso prioritario','Peligro no especificado próximo','Fin de todas las prohibiciones','Ceda el paso'], correct:1, explanation:'El triángulo con signo de exclamación advierte de un peligro próximo no especificado que requiere atención especial.' },
      { id:'S07', q:'¿Qué señal obliga a detenerse completamente antes de una intersección?', options:['Ceda el paso (triángulo invertido)','STOP (octógono rojo)','Semáforo en ámbar','Línea discontinua en el suelo'], correct:1, explanation:'La señal STOP (octógono rojo) obliga a una detención COMPLETA, aunque no haya tráfico en la vía con prioridad.' },
      { id:'S08', q:'¿Qué indica la señal "Ceda el paso"?', options:['Detenerse completamente','Ceder el paso a los vehículos de la vía, parando si es necesario','Tener prioridad de paso','Reducir la velocidad a 30 km/h'], correct:1, explanation:'"Ceda el paso" significa dar prioridad a los vehículos de la vía a la que accedes. Puedes continuar si no hay nadie, pero debes parar si fuera necesario.' },
      { id:'S09', q:'¿Qué indica una señal de velocidad tachada con raya diagonal?', options:['Que el límite baja a la mitad','Fin de esa limitación de velocidad','Que la señal no es válida','Zona de obras'], correct:1, explanation:'Una señal de velocidad con raya diagonal indica el fin de esa limitación específica. Se recupera el límite genérico de la vía.' },
      { id:'S10', q:'¿Cuándo deben obedecerse los paneles electrónicos de tráfico?', options:['Solo de noche','Siempre que estén activados, prevalecen sobre las señales fijas','Solo si las fijas dicen lo contrario','Son meramente orientativos'], correct:1, explanation:'Las señales variables (paneles electrónicos) prevalecen sobre las señales fijas cuando están en funcionamiento.' },
      { id:'S11', q:'¿Qué prohíbe la señal de adelantamiento?', options:['Circular por ese carril','Adelantar a vehículos de motor','Que la velocidad máxima se reduzca a la mitad','Que hay obras en la calzada'], correct:1, explanation:'La señal de prohibición de adelantamiento prohíbe sobrepasar a los vehículos de motor en el mismo sentido, salvo ciclomotores y bicicletas.' },
      { id:'S12', q:'Una señal rectangular de fondo azul con una "P" blanca indica:', options:['Prohibido aparcar','Aparcamiento permitido','Paso de peatones','Zona de policía'], correct:1, explanation:'La señal de fondo azul con "P" blanca indica zona de aparcamiento permitido. Puede incluir restricciones de tiempo.' },
      { id:'S13', q:'¿Qué indican las marcas viales en zigzag pintadas en el suelo?', options:['Zona de obras','Prohibición de estacionar en esa zona','Zona de maniobras peligrosas','Línea de parada para bicicletas'], correct:1, explanation:'Las marcas en zigzag indican prohibición de estacionar, habitualmente cerca de colegios, hospitales o pasos de peatones.' },
      { id:'S14', q:'¿Qué indica la señal de "carretera con prioridad"?', options:['STOP en cada cruce','Fondo amarillo con rombo blanco — prioridad en intersecciones','Líneas continuas en el suelo','Señal de flecha azul'], correct:1, explanation:'La señal cuadrada con borde amarillo y rombo blanco indica que esa vía tiene prioridad en todos los cruces.' },
      { id:'S15', q:'¿Qué indica la señal de paso para peatones (líneas paralelas en el suelo)?', options:['Peatones, prohibido cruzar','Zona para peatones que respetan el tráfico','Paso con prioridad para peatones sobre vehículos','Zona de bicicletas'], correct:2, explanation:'El paso de peatones señalizado otorga preferencia a los peatones. Los conductores deben ceder el paso a quien cruce o vaya a cruzar.' },
      { id:'S16', q:'¿Qué indica en un semáforo la luz verde intermitente?', options:['Circular sin restricciones','El semáforo va a cambiar a ámbar pronto','Zona escolar, circular despacio','Solo para vehículos de emergencia'], correct:1, explanation:'La luz verde intermitente avisa que el semáforo va a cambiar a ámbar. Es señal de precaución.' },
      { id:'S17', q:'La señal STOP obliga a:', options:['Reducir la velocidad a 20 km/h','Detenerse completamente y ceder el paso','Solo ceder el paso sin detenerse','Tocar el claxon y continuar'], correct:1, explanation:'STOP exige una detención COMPLETA (velocidad cero) antes de la línea de detención, aunque no haya tráfico en la intersección.' },
      { id:'S18', q:'¿Qué significa una zona de estacionamiento limitado (zona azul)?', options:['Estacionamiento gratuito ilimitado','Estacionamiento permitido por tiempo limitado con ticket','Prohibición total de aparcar','Solo para residentes sin pago'], correct:1, explanation:'Las zonas azules permiten estacionar durante tiempo máximo indicado previo pago en parquímetro o uso de disco de aparcamiento.' },
      { id:'S19', q:'¿Qué señal indica el fin de autovía?', options:['Que la carretera termina completamente','Que termina el tramo de autovía y empieza carretera convencional','Que hay un peaje próximo','Fin del límite de 120 km/h'], correct:1, explanation:'La señal de fin de autovía indica que las calzadas separadas terminan y comienza una carretera convencional.' },
      { id:'S20', q:'Una línea continua en el centro de la calzada prohíbe:', options:['Girar a la derecha','Cruzarla o circular sobre ella','Adelantar con precaución','Circular a más de 90 km/h'], correct:1, explanation:'La línea longitudinal continua prohíbe cruzarla o circular sobre ella, impidiendo el adelantamiento o invasión del carril contrario.' },
      { id:'S21', q:'¿Qué significa la línea discontinua en el centro de la calzada?', options:['Prohibición absoluta de adelantar','Puedes cruzarla para adelantar si no hay peligro','Límite de velocidad reducido','Carril reversible'], correct:1, explanation:'La línea discontinua indica que puedes cruzarla para adelantar, siempre que la visibilidad y el tráfico lo permitan.' },
      { id:'S22', q:'La doble línea mixta (continua + discontinua) indica:', options:['Siempre prohibido adelantar en ambos sentidos','El que tiene la línea CONTINUA a su lado no puede cruzarla; el de la DISCONTINUA sí puede','Zona de obras','Carril reversible'], correct:1, explanation:'La doble línea mixta prohíbe cruzar al conductor que tiene la CONTINUA a su lado, pero permite al que tiene la DISCONTINUA.' },
      { id:'S23', q:'Si te encuentras un semáforo en verde y una señal vertical de STOP al lado, ¿qué debes hacer?', image:'semaforo_stop.jpg', options:['Detenerme siempre por la señal de STOP','Pasar sin detenerme, porque el semáforo prevalece sobre la señal vertical','Detenerme solo si vienen vehículos','Pasar pero reduciendo la velocidad a 10 km/h'], correct:1, explanation:'Según el orden de prioridad de las señales, los semáforos prevalecen sobre las señales verticales de prioridad (como el STOP o el Ceda el Paso).' },
      { id:'S24', q:'Una señal circular de borde rojo con una flecha hacia la izquierda tachada prohíbe girar a la izquierda. ¿Prohíbe también cambiar el sentido de la marcha?', image:'prohibido_izquierda.jpg', options:['No, solo prohíbe girar a la izquierda','Sí, prohíbe girar a la izquierda y también cambiar el sentido de la marcha','Solo prohíbe cambiar el sentido a los camiones','Depende de si hay línea continua en el suelo'], correct:1, explanation:'La señal de prohibido girar a la izquierda prohíbe el giro y también el cambio de sentido de la marcha, ya que para cambiar de sentido hay que realizar un giro a la izquierda.' },
      { id:'S25', q:'Una señal cuadrada de fondo azul con una cifra en blanco indica:', options:['Velocidad mínima obligatoria','Velocidad máxima permitida','Velocidad máxima recomendada, aunque las condiciones sean favorables','Fin de la limitación de velocidad'], correct:2, explanation:'Las señales cuadradas azules indican recomendaciones. En este caso, recomienda no superar esa velocidad aunque las condiciones de la vía y el clima sean favorables.' },
      { id:'S26', q:'¿Qué prohíbe una línea amarilla continua pintada en el bordillo de la calzada?', options:['Estacionar, pero permite parar','Parar y estacionar','Circular por ese carril','Adelantar'], correct:1, explanation:'Una línea amarilla continua en el bordillo o junto al borde de la calzada significa que está prohibido tanto parar como estacionar en toda su longitud.' },
      { id:'S27', q:'La señal de "Peligro por animales domésticos" lleva debajo un panel complementario con la palabra "Cañada". ¿Qué significa?', options:['Que los animales tienen preferencia de paso','Que está prohibido el paso a vehículos a motor','Que hay una granja cerca','Que los vehículos deben detenerse obligatoriamente siempre'], correct:0, explanation:'Si la señal de paso de animales domésticos va acompañada del panel "cañada", indica que el paso es una cañada y los animales tienen preferencia de paso sobre los vehículos.' },
      { id:'S28', q:'Un semáforo circular tiene la luz roja encendida y una flecha verde adicional apuntando a la derecha. ¿Puedes girar a la derecha?', options:['No, porque la luz principal es roja','Sí, teniendo preferencia absoluta','Sí, pero cediendo el paso a los vehículos que circulen por el carril al que me incorporo','Solo si voy conduciendo un vehículo de transporte público'], correct:2, explanation:'La flecha verde sobre fondo negro permite avanzar en esa dirección, cualquiera que sea la luz principal, pero cediendo el paso a los vehículos que circulen por el carril al que se incorpora.' },
      { id:'S29', q:'¿Qué anula la señal blanca circular con una franja negra en diagonal (Fin de prohibiciones)?', options:['Todas las prohibiciones que hubiera en la vía','Todas las prohibiciones de carácter local para vehículos en movimiento','El límite genérico de velocidad de la vía','Las prohibiciones de aparcamiento'], correct:1, explanation:'Esta señal indica el fin de todas las prohibiciones de carácter local dictadas por anteriores señales, referidas a los vehículos en movimiento.' },
      { id:'S30', q:'¿Qué debes hacer ante un paso a nivel con dos luces rojas intermitentes alternativamente?', image:'paso_nivel_luces.jpg', options:['Reducir la velocidad y cruzar con precaución','Tocar el claxon antes de pasar','Detenerme obligatoriamente, prohíben temporalmente el paso','Ceder el paso a los trenes pero sin obligación de parar'], correct:2, explanation:'Dos luces rojas intermitentes alternativamente prohíben temporalmente el paso, por aproximación de un tren, puente móvil, extinción de incendios o aviones a baja altura.' },
      { id:'S31', q:'¿Qué indica la señal de Peligro por Pavimento Deslizante?', options:['Que el pavimento está resbaladizo únicamente por hielo','Que el pavimento puede resultar muy resbaladizo por cualquier causa (lluvia, nieve, etc.)','Que hay gravilla suelta en la calzada','Que se aproxima una zona de curvas sucesivas'], correct:1, explanation:'Advierte del peligro por la proximidad de un tramo de vía cuyo pavimento puede resultar muy deslizante (por cualquier causa, no solo hielo o lluvia).' },
      { id:'S32', q:'Una señal con una flecha apuntando hacia arriba y el texto "Vía de telepeaje", ¿qué indica?', options:['Que es obligatorio el pago con telepeaje en ese carril','Que se puede pagar en efectivo o con telepeaje','Que ese carril está cerrado','Que el peaje es gratuito'], correct:0, explanation:'Si la señal es redonda (obligación) con la T de telepeaje, indica que ese carril es EXCLUSIVO y obligatorio para vehículos equipados con sistema de telepeaje operativo.' },
      { id:'S33', q:'¿Qué significa la señal de Stop manual que muestra un guardia civil o agente de tráfico?', options:['Obligación de detenerse para los vehículos a los que el agente dirija la señal','Detención general de todo el tráfico de la vía','Obligación de reducir la velocidad al pasar a su altura','Aviso de un accidente a 500 metros'], correct:0, explanation:'La señal de Stop (paleta o mano) mostrada por un agente indica la obligación de detenerse a los usuarios a los que dirija la señal.' },
      { id:'S34', q:'¿Qué indica un agente de tráfico con el brazo levantado verticalmente?', options:['Obliga a detenerse a todos los usuarios que se acerquen al agente, salvo que ya no puedan hacerlo con seguridad','Obliga a detenerse solo a los vehículos que vienen de frente','Da prioridad de paso a los vehículos que vienen por detrás','Avisa de un cambio de dirección obligatorio'], correct:0, explanation:'El brazo levantado verticalmente obliga a detenerse a TODOS los usuarios que se acerquen al agente, sea cual sea la dirección de la que procedan, salvo que ya estén tan cerca que no puedan detenerse en condiciones de seguridad.' },
      { id:'S35', q:'¿Qué significa si un agente de tráfico balancea una luz roja?', options:['Que se aproxima un vehículo de emergencias','Obliga a detenerse a los usuarios hacia los que el agente dirija la luz','Que la calzada está cerrada completamente','Que debes encender las luces de emergencia'], correct:1, explanation:'El balanceo de una luz roja o amarilla obliga a detenerse a los usuarios de la vía hacia los que el agente dirija la luz.' },
      { id:'S36', q:'¿Qué indica el toque de silbato corto y frecuente de un agente?', options:['Reanudar la marcha','Detenerse','Reducir la velocidad','Apartarse al arcén'], correct:1, explanation:'Los toques de silbato cortos y frecuentes indican la obligación de DETENERSE. (Recuerda: Corto = Cortar la marcha/Parar).' },
      { id:'S37', q:'¿Y un toque de silbato largo?', options:['Detener el vehículo','Reanudar la marcha','Acelerar','Aparcar el vehículo'], correct:1, explanation:'Un toque largo de silbato indica la reanudación de la marcha. (Recuerda: Largo = Vía Libre).' },
      { id:'S38', q:'Una bandera roja empuñada por el personal de obras indica:', options:['Obligación de detenerse','Peligro por obras, pero sin obligación de parar','Circulación en sentido alternativo','Preferencia para los vehículos pesados'], correct:0, explanation:'Una bandera roja empuñada por personal en la vía obliga a detenerse a los usuarios a los que vaya dirigida.' },
      { id:'S39', q:'¿Qué indica un semáforo cuadrado para vehículos (semáforo de carril) con un aspa roja?', options:['Que el semáforo está averiado','Prohíbe ocupar ese carril y los vehículos que lo ocupen deben abandonarlo en el tiempo más breve posible','Que la velocidad máxima es de 10 km/h','Que el carril es de sentido único'], correct:1, explanation:'Un aspa roja en un semáforo de carril prohíbe ocupar dicho carril. Quienes circulen por él deben abandonarlo con seguridad lo antes posible.' },
      { id:'S40', q:'¿Qué indica la luz amarilla fija en un semáforo?', options:['Paso libre con precaución','Obliga a detenerse en las mismas condiciones que la luz roja, a menos que no se pueda hacer con seguridad','Prioridad de paso','El semáforo va a cambiar a verde'], correct:1, explanation:'La luz amarilla no intermitente (fija) obliga a detenerse como si fuera roja, salvo que el vehículo esté tan cerca de la intersección que no pueda frenar con seguridad.' },
      { id:'S41', q:'Una luz amarilla intermitente en un semáforo, ¿qué te exige?', options:['Detenerme siempre','Extremar la precaución y, en su caso, ceder el paso','Acelerar para despejar el cruce','Tener preferencia absoluta sobre cualquier vehículo'], correct:1, explanation:'La luz amarilla intermitente exige precaución, ceder el paso si es necesario y no exime de cumplir otras señales como STOP o Ceda el paso que pueda haber en la intersección.' },
      { id:'S42', q:'En un semáforo, una flecha negra sobre un fondo de luz roja intermitente o fija, ¿cambia el significado de la luz roja?', options:['Sí, permite el paso en esa dirección','No cambia el significado, solo limita la prohibición a la dirección indicada por la flecha','Da prioridad sobre los peatones','Solo afecta a los autobuses'], correct:1, explanation:'Una flecha negra sobre luz roja no te permite pasar. Simplemente indica que la prohibición de pasar (la luz roja) se aplica exclusivamente al carril que toma la dirección de la flecha.' },
      { id:'S43', q:'Una señal circular de borde rojo con un camión negro en el centro indica:', options:['Prohibición de entrada a cualquier camión o furgón','Prohibición de entrada solo a camiones de más de 3.500 kg de MMA','Peligro por circulación frecuente de camiones','Estacionamiento reservado para camiones'], correct:0, explanation:'Prohíbe el acceso a TODA CLASE de camiones y furgones, independientemente de su masa máxima autorizada.' },
      { id:'S44', q:'¿Qué prohíbe la señal de "Entrada prohibida a ciclomotores"?', options:['A ciclomotores de dos ruedas únicamente','A ciclomotores, cuadriciclos ligeros y vehículos para personas de movilidad reducida','A bicicletas y ciclomotores','A cualquier vehículo de dos ruedas'], correct:1, explanation:'Esta señal prohíbe el acceso no solo a ciclomotores de dos ruedas, sino también a ciclomotores de tres ruedas, cuadriciclos ligeros y vehículos para personas de movilidad reducida.' },
      { id:'S45', q:'¿Qué indica una señal de límite de velocidad acompañada de una señal de peligro por curvas?', options:['Que el límite de velocidad rige en toda la carretera','Que el límite rige únicamente en el tramo donde está el peligro (la curva)','Que en las curvas la velocidad se reduce a la mitad','Que el límite rige hasta encontrar otra señal de velocidad'], correct:1, explanation:'Cuando una señal de límite de velocidad se coloca en el mismo poste (o panel) bajo una señal de advertencia de peligro, el límite finaliza cuando termina el peligro advertido.' },
      { id:'S46', q:'Una señal de "Fin de prohibición de adelantamiento", ¿qué significa?', options:['Que ya se puede adelantar sin precauciones','Que se recupera la norma general que permite adelantar, siempre que sea seguro','Que hay dos carriles para mi sentido','Que finaliza la autopista'], correct:1, explanation:'Indica que termina el tramo de prohibición de adelantamiento. Por lo tanto, vuelve a aplicarse la norma general que permite adelantar si se cumplen todas las condiciones de seguridad.' },
      { id:'S47', q:'La señal cuadrada con fondo azul e indicando "30" se llama "Velocidad Mínima". ¿Cierto o falso?', options:['Cierto, prohíbe circular a menos de 30','Falso, es la señal de "Velocidad Recomendada"','Falso, es la señal de "Fin de limitación"','Falso, es exclusiva de autopistas'], correct:1, explanation:'La señal cuadrada azul indica VELOCIDAD RECOMENDADA. La señal circular azul es la que indica Velocidad Mínima Obligatoria.' },
      { id:'S48', q:'Una señal cuadrada azul con un surtidor de gasolina indica:', options:['Estación de servicio obligatoria','Estación de servicio en los alrededores','Taller mecánico','Lavadero de coches'], correct:1, explanation:'Indica la situación de un surtidor de carburante o estación de servicio.' },
      { id:'S49', q:'¿Qué significa la señal que tiene dos coches, uno negro a la derecha y uno rojo a la izquierda?', options:['Prioridad al sentido contrario','Preferencia respecto al sentido contrario','Peligro por estrechamiento','Prohibido adelantar'], correct:3, explanation:'La señal circular de borde rojo con un turismo negro a la derecha y uno rojo a la izquierda prohíbe a todos los vehículos de motor el adelantamiento.' },
      { id:'S50', q:'¿Qué marca vial se utiliza para separar los sentidos de circulación en una vía?', options:['Línea transversal continua','Línea longitudinal (continua o discontinua) en el centro de la calzada','Marcas en zigzag','Líneas de borde de calzada'], correct:1, explanation:'Las líneas longitudinales centrales (ya sean continuas o discontinuas) separan los carriles y, en vías de doble sentido, separan los sentidos de circulación.' },
      { id:'S51', q:'¿Puedes pisar un cebreado (zonas con líneas diagonales blancas) pintado en el suelo?', options:['Sí, para adelantar','No, ningún vehículo puede entrar ni circular sobre un cebreado','Sí, pero solo los vehículos obligados a circular por el arcén (ej. ciclomotores)','Sí, para aparcar momentáneamente'], correct:2, explanation:'Por regla general no se puede circular sobre los cebreados (franjas oblicuas enmarcadas). Sin embargo, los vehículos obligados a circular por el arcén SÍ pueden utilizarlos si es seguro.' },
      { id:'S52', q:'Una línea continua que tiene adosada otra discontinua (doble línea mixta), ¿a qué línea debes obedecer?', options:['A la más cercana a mi vehículo (la situada en mi lado)','A la más restrictiva siempre (la continua)','A la discontinua, que permite cruzar','A ninguna de las dos'], correct:0, explanation:'Cuando hay dos líneas juntas, una continua y otra discontinua, el conductor solo debe tener en cuenta (obedecer) la línea que esté situada en su lado.' },
      { id:'S53', q:'¿Qué es una marca de bifurcación?', options:['Una flecha en el suelo con dos puntas que indica que el carril permite seguir de frente o girar','Un aviso acústico','Una señal luminosa en túneles','Una línea amarilla en zigzag'], correct:0, explanation:'Es una flecha de selección de carriles que se bifurca, indicando que desde ese carril se puede seguir de frente o tomar la dirección de la bifurcación.' },
      { id:'S54', q:'En una intersección, ¿qué señal prevalece: el Ceda el Paso o el semáforo en amarillo intermitente?', options:['El semáforo amarillo intermitente, porque los semáforos siempre prevalecen','El Ceda el Paso, porque el amarillo intermitente te obliga a extremar precaución y cumplir las demás señales','Prevalecen ambas anulándose mutuamente','Ninguna, se aplica la norma de ceder a la derecha'], correct:1, explanation:'Una excepción a la regla de prioridad: si hay un semáforo amarillo intermitente y una señal vertical de Stop o Ceda el paso, DEBES cumplir la señal vertical.' },
      { id:'S55', q:'¿Qué indica un panel rectangular con rayas diagonales rojas y blancas alternas?', options:['Zona de obras','Fin de autovía','Peligro de nieve','Paso a nivel próximo'], correct:0, explanation:'Los paneles rectangulares u horizontales con franjas alternas rojas y blancas indican la presencia de una zona de obras o un obstáculo en la calzada.' },
      { id:'S56', q:'Una marca vial amarilla en zigzag pintada a lo largo del borde de la calzada indica:', options:['Prohibición absoluta de parar y estacionar','Lugar donde el estacionamiento está prohibido, pero se permite la parada (zona de carga/descarga o paradas de bus)','Carril reservado para bicicletas','Zona exclusiva para peatones'], correct:1, explanation:'La línea amarilla en zigzag indica que está prohibido ESTACIONAR en esa zona, generalmente reservada para algún uso especial que sí permite la parada momentánea.' },
      { id:'S57', q:'La señal triangular con un tranvía en su interior advierte de:', options:['Peligro por cruce con una línea de tranvía, el cual tiene prioridad de paso','Vía exclusiva para tranvías','Estación de tren cercana','Peligro por cables de alta tensión'], correct:0, explanation:'Peligro por la proximidad de un cruce con una línea de tranvía, recordando que los tranvías tienen prioridad de paso.' },
      { id:'S58', q:'Una señal cuadrada con la inscripción "SOS" y un teléfono dibujado indica:', options:['Puesto de socorro médico','Puesto de socorro y teléfono de emergencias','Obligación de llamar en caso de avería','Estación de policía'], correct:1, explanation:'Indica la existencia de un poste de SOS (teléfono de emergencias) para contactar con los servicios de rescate o asistencia en carretera.' },
      { id:'S59', q:'¿Qué forma tiene la señal que indica "Intersección con prioridad sobre vía a la derecha"?', options:['Triangular con borde rojo (peligro)','Circular con borde rojo (prohibición)','Cuadrada de fondo azul (información)','Octogonal (Stop)'], correct:0, explanation:'Las señales que advierten de un peligro por una intersección son triangulares con el borde rojo. En este caso, lleva un símbolo grueso cruzado por una línea más fina por la derecha.' },
    ],
    'normas': [
      { id:'N01', q:'En una vía con varios carriles para el mismo sentido, ¿por cuál debes circular habitualmente?', options:['Por el carril izquierdo','Por el carril derecho','Por el carril central','Por cualquiera que esté libre'], correct:1, explanation:'La norma general obliga a circular por el carril más a la derecha que esté libre de obstáculos.' },
      { id:'N02', q:'¿Qué debes hacer cuando el semáforo cambia a ámbar y aún puedes parar con seguridad?', options:['Acelerar para cruzar antes del rojo','Detenerte antes de la línea de detención','Mantener la velocidad actual','Tocar el claxon y continuar'], correct:1, explanation:'El ámbar significa "prepárate a parar". Si puedes hacerlo sin peligro, debes detener el vehículo.' },
      { id:'N03', q:'¿Está permitido circular marcha atrás en autopistas y autovías?', options:['Sí, hasta 50 metros en el arcén','Sí, si hay emergencia','No, nunca está permitido','Solo de noche con precaución'], correct:2, explanation:'La marcha atrás está expresamente prohibida en autopistas y autovías. Si te pasas de la salida, debes continuar hasta la siguiente.' },
      { id:'N04', q:'¿Cuándo está permitido circular por el carril izquierdo?', options:['Siempre que se quiera','Solo para adelantar o cuando el tráfico lo impide usar el derecho','Solo en zonas urbanas','Nunca está permitido'], correct:1, explanation:'El carril izquierdo es de adelantamiento. Solo se debe usar para adelantar o cuando la densidad de tráfico impide usar el derecho.' },
      { id:'N05', q:'¿Se puede circular con el motor apagado o en punto muerto cuesta abajo?', options:['Sí, para ahorrar combustible','Sí, si no hay tráfico','No, es peligroso y está prohibido','Solo en zona urbana'], correct:2, explanation:'Circular con motor apagado o en punto muerto está prohibido: se pierde asistencia de dirección y frenos.' },
      { id:'N06', q:'Al cruzar una vía de ferrocarril sin barreras, ¿qué debes hacer?', options:['Cruzar rápidamente','Reducir velocidad, mirar a ambos lados y cruzar solo si está libre','Ceder el paso solo si se ve el tren','Tocar el claxon antes de cruzar'], correct:1, explanation:'En pasos a nivel sin barreras debes reducir velocidad, asegurarte de que no viene ningún tren mirando a ambos lados.' },
      { id:'N07', q:'¿Cuál es la separación lateral mínima al adelantar a un ciclista?', options:['0,5 metros','1 metro','1,5 metros','2 metros'], correct:2, explanation:'La ley exige una separación lateral mínima de 1,5 metros al adelantar a un ciclista.' },
      { id:'N08', q:'¿Qué debes hacer si una ambulancia con señales activas te alcanza por detrás?', options:['Continuar a la misma velocidad','Acelerar para no obstaculizarla','Apartarte hacia la derecha y dejarla pasar','Detenerte inmediatamente'], correct:2, explanation:'Ante vehículos de emergencia en servicio, debes apartarte hacia la derecha para dejarles paso libre.' },
      { id:'N09', q:'¿Están obligados a usar el cinturón los ocupantes de la fila trasera en autopista?', options:['No, solo en asientos delanteros','Sí, siempre','Solo si el conductor lo decide','Solo en viajes de más de 100 km'], correct:1, explanation:'El cinturón es obligatorio para todos los ocupantes del vehículo en todos los asientos.' },
      { id:'N10', q:'¿Es obligatorio que los niños menores de 135 cm usen sistema de retención infantil?', options:['Solo menores de 3 años','Solo en asientos delanteros','Sí, en todos los asientos y cualquier tipo de vía','Solo en autopistas'], correct:2, explanation:'Los menores de 135 cm deben usar un sistema de retención homologado en todos los asientos y en cualquier tipo de vía.' },
      { id:'N11', q:'¿Está permitido usar el teléfono móvil en mano mientras se conduce?', options:['Sí, si se conduce despacio','Sí, si es por poco tiempo','No, está prohibido y supone pérdida de 6 puntos','Solo si el vehículo está parado en semáforo'], correct:2, explanation:'Usar el móvil en mano mientras se conduce está prohibido y conlleva la pérdida de 6 puntos del carnet.' },
      { id:'N12', q:'¿Qué debes hacer al acercarte a un paso de peatones con personas esperando?', options:['Acelerar para pasar antes','Tocar el claxon para advertirles','Reducir velocidad y ceder el paso','Mantener la velocidad si no están cruzando'], correct:2, explanation:'Los peatones tienen preferencia en los pasos señalizados. Debes reducir velocidad y detenerte si alguien quiere cruzar.' },
      { id:'N13', q:'¿Se puede aparcar encima de la acera aunque sea parcialmente?', options:['Sí, si sobresale menos de 1 metro','Sí, si el paso peatonal queda libre','No, no se puede aparcar sobre la acera','Solo en zonas sin señalización'], correct:2, explanation:'Aparcar total o parcialmente sobre la acera está prohibido ya que obstruye el paso de peatones.' },
      { id:'N14', q:'En una rotonda, ¿qué conductor tiene preferencia de paso?', options:['El que entra a la rotonda','El que ya circula dentro de la rotonda','El que viene por la derecha','El vehículo de mayor tamaño'], correct:1, explanation:'En una rotonda debidamente señalizada, los vehículos que ya circulan dentro tienen preferencia sobre los que quieren entrar.' },
      { id:'N15', q:'¿Cuántos triángulos de preseñalización de peligro son necesarios?', options:['Uno','Dos','Tres','Ninguno, son opcionales'], correct:1, explanation:'Es obligatorio llevar dos triángulos de preseñalización. Para vehículos de menos de 3.500 kg es obligatorio llevar al menos uno.' },
      { id:'N16', q:'¿Qué significa una zona 30?', options:['Zona donde se puede aparcar 30 minutos','Zona con límite de velocidad de 30 km/h','Zona con 30 plazas de aparcamiento','Zona de carga y descarga de 30 minutos'], correct:1, explanation:'Las zonas 30 son áreas urbanas con velocidad máxima de 30 km/h para mejorar la seguridad de peatones y ciclistas.' },
      { id:'N17', q:'¿Cuándo pueden circular los peatones por la calzada?', options:['Nunca, deben usar siempre la acera','Cuando no hay acera o está impracticable, circulando por la izquierda','Siempre que no haya coches','Solo de noche'], correct:1, explanation:'Los peatones pueden circular por la calzada cuando no exista acera o esté en malas condiciones, haciéndolo por la izquierda.' },
      { id:'N18', q:'¿Qué debe hacer un conductor antes de abrir la puerta del vehículo estacionado?', options:['Nada, tiene derecho a abrir la puerta','Asegurarse de que no viene nadie por la vía o acera','Abrir rápidamente para no interrumpir el tráfico','Solo mirar si hay coches, no ciclistas'], correct:1, explanation:'Antes de abrir la puerta, verifica que no viene nadie: vehículos, ciclistas, peatones. Abrirla sin comprobar puede causar accidentes.' },
      { id:'N19', q:'¿Qué se entiende por velocidad de seguridad?', options:['El límite señalizado en cada vía','La velocidad que permite controlar el vehículo ante cualquier incidencia previsible','La velocidad recomendada por el fabricante','50 km/h en cualquier circunstancia'], correct:1, explanation:'La velocidad de seguridad es la que permite al conductor dominar el vehículo y detenerlo ante cualquier incidencia previsible.' },
      { id:'N20', q:'¿Qué debes hacer al llegar a un paso a nivel con barreras bajadas?', options:['Cruzar rápidamente antes de que cierre completamente','Esperar hasta que las barreras estén completamente levantadas','Rodear las barreras si hay espacio','Tocar el claxon y cruzar'], correct:1, explanation:'Con barreras bajadas o bajándose, debes esperar hasta que estén completamente levantadas. Nunca rodees las barreras.' },
      { id:'N21', q:'¿Está permitido parar en segunda fila?', options:['Si se deja a alguien en menos de 2 minutos','Nunca, siempre es una infracción','Si el conductor permanece al volante y no obstruye el tráfico','Si es zona azul y se paga el parquímetro'], correct:2, explanation:'Parar en segunda fila es infracción en casi todos los casos. Solo puede tolerarse momentáneamente si el conductor permanece al volante.' },
      { id:'N22', q:'¿Qué indica la línea de STOP pintada en el suelo?', options:['Reducir la velocidad','Detenerse completamente antes de la línea','Tener prioridad de paso','Hay un semáforo próximo'], correct:1, explanation:'La línea de STOP obliga a una detención completa antes de la misma. No basta con reducir la velocidad.' },
      { id:'N23', q:'¿Es obligatorio el uso del casco en motocicleta siempre?', options:['Solo a más de 50 km/h','Solo en carretera interurbana','Sí, siempre, en cualquier vía y velocidad','Solo para el conductor, no el acompañante'], correct:2, explanation:'El casco homologado es obligatorio para el conductor y el pasajero de motocicleta en cualquier tipo de vía.' },
      { id:'N24', q:'Si vas a girar a la izquierda en una vía con carril central compartido, ¿qué debes hacer?', options:['Girar directamente desde el carril derecho','Entrar al carril central para esperar a que pase el tráfico contrario','Adelantar a los vehículos y girar','Esperar en el arcén'], correct:1, explanation:'El carril central compartido sirve para que los vehículos que van a girar a la izquierda esperen el momento oportuno.' },
      { id:'N25', q:'¿Cuándo tiene preferencia el autobús urbano al incorporarse desde una parada?', options:['Ninguna, debe esperar a que no haya tráfico','Prioridad sobre los vehículos del carril adyacente en zona urbana','Prioridad sobre todos en cualquier vía','Solo si señaliza con intermitente'], correct:1, explanation:'Los autobuses de transporte colectivo tienen prioridad al reincorporarse desde una parada señalizada en zona urbana.' },
      { id:'N26', q:'¿Qué debes hacer si el vehículo de delante frena bruscamente?', options:['Tocar el claxon y frenar','Frenar inmediatamente y verificar que mantienes suficiente distancia de seguridad','Cambiar de carril sin señalizar','Acelerar para no ser alcanzado por el de detrás'], correct:1, explanation:'Si el vehículo de delante frena bruscamente, debes frenar. La distancia de seguridad existe precisamente para tener margen de reacción.' },
      { id:'N27', q:'¿Qué es el tiempo de reacción?', options:['El tiempo que tarda en frenar el vehículo completamente','El tiempo que transcurre entre percibir el peligro y actuar sobre los mandos del vehículo','El tiempo mínimo entre tests en la DGT','El tiempo legal para recuperar el carnet por puntos'], correct:1, explanation:'El tiempo de reacción es el que transcurre entre que el conductor percibe el peligro y comienza a actuar sobre los mandos. En condiciones normales ronda 0,75-1 segundo.' },
      { id:'N28', q:'¿Cuándo es obligatorio llevar chaleco reflectante?', options:['No es obligatorio, solo recomendable','Es obligatorio y debe ponerse ANTES de salir del vehículo en caso de avería o accidente','Solo si se conduce de noche','Solo en autopistas y autovías'], correct:1, explanation:'Es obligatorio llevar al menos un chaleco reflectante. En caso de avería o accidente, debes ponértelo ANTES de salir del vehículo.' },
      { id:'N29', q:'¿Quiénes pueden circular por un carril para Vehículos de Alta Ocupación (VAO)?', options:['Solo turismos con un mínimo de ocupantes, motos, vehículos mixtos y autobuses','Cualquier turismo sea cual sea el número de ocupantes','Camiones de menos de 3.500 kg y furgonetas','Cualquier vehículo si hay atasco en los demás carriles'], correct:0, explanation:'El carril VAO está reservado principalmente para motocicletas, turismos y vehículos mixtos adaptables que lleven el número mínimo de ocupantes indicado. También pueden entrar autobuses, vehículos V-15 (movilidad reducida) y vehículos con etiqueta Cero.' },
      { id:'N30', q:'Si tu vehículo queda inmovilizado en una autopista por avería, ¿puedes ser remolcado por otro turismo?', options:['Sí, hasta la salida más próxima','No, está totalmente prohibido','Sí, si usamos una eslinga homologada','Sí, pero solo de día'], correct:1, explanation:'El Reglamento General de Circulación prohíbe expresamente que un vehículo a motor remolque a otro, excepto a los vehículos grúa específicamente destinados a ello.' },
    ],
    'prioridad': [
      { id:'P01', q:'En una intersección sin señalizar, ¿a quién cedes el paso?', options:['A los que vienen de frente','A los que vienen por tu derecha','A los vehículos más grandes','Al que llegó primero'], correct:1, explanation:'La norma de la derecha: en intersecciones sin señalizar, cede el paso a los vehículos que se aproximan por tu derecha.' },
      { id:'P02', q:'¿Qué vehículos tienen prioridad de paso absoluta cuando circulan en emergencia?', options:['Solo las ambulancias','Ambulancias, bomberos y policía con señales activas','Solo la policía','Todos los vehículos grandes'], correct:1, explanation:'Los vehículos de emergencia tienen prioridad absoluta cuando circulan con señales acústicas y/o luminosas de emergencia.' },
      { id:'P03', q:'¿Tienen los tranvías prioridad de paso sobre los demás vehículos?', options:['No, siguen las mismas normas','Sí, salvo señal en contrario','Solo en los cruces señalizados','Solo cuando llevan muchos pasajeros'], correct:1, explanation:'Los tranvías tienen prioridad de paso sobre los demás vehículos, salvo que una señal indique lo contrario.' },
      { id:'P04', q:'¿Qué vehículo tiene prioridad en un cruce entre vía principal y secundaria?', options:['El que va más rápido','El que circula por la vía principal','El que viene por la derecha','El mayor en tamaño'], correct:1, explanation:'Los vehículos que circulan por la vía principal tienen prioridad sobre los procedentes de vías secundarias.' },
      { id:'P05', q:'Un vehículo que sale de un garaje a la vía pública, ¿a quién debe ceder el paso?', options:['Solo a los peatones','A nadie, tiene derecho de salida','A todos los vehículos y peatones de la vía','Solo a los vehículos que vengan por la izquierda'], correct:2, explanation:'Al salir de un garaje, el conductor debe ceder el paso a todos los usuarios de la vía pública.' },
      { id:'P06', q:'¿Qué prioridad tienen los ciclistas en un carril bici señalizado al cruzar la calzada?', options:['Siempre ceden el paso a vehículos a motor','Sí, los vehículos deben cederles el paso','Solo si llevan casco','Solo si el carril bici tiene semáforo'], correct:1, explanation:'Los ciclistas en un carril bici señalizado tienen preferencia sobre los vehículos a motor al cruzar la calzada.' },
      { id:'P07', q:'Los vehículos de vía pavimentada frente a los de vía no pavimentada:', options:['El de la vía no pavimentada tiene prioridad por ser más estrecha','El de la vía pavimentada tiene prioridad','Tienen la misma preferencia','Depende del tamaño del vehículo'], correct:1, explanation:'Los vehículos que circulan por vías pavimentadas tienen prioridad sobre los procedentes de vías sin pavimentar.' },
      { id:'P08', q:'¿Cuándo pueden cruzar los peatones fuera de un paso señalizado?', options:['Nunca, siempre deben usar el paso','Cuando no haya paso próximo y cedan el paso a los vehículos','Cuando no vengan coches a la vista','Solo en zona urbana'], correct:1, explanation:'Los peatones pueden cruzar fuera de los pasos si no hay uno próximo, pero deben ceder el paso a los vehículos.' },
      { id:'P09', q:'En una vía estrecha con pendiente, ¿quién cede el paso?', options:['El que viene de frente','El que baja la pendiente','El que sube cede al que baja','El de mayor tamaño cede al pequeño'], correct:2, explanation:'En vías estrechas con pendiente, el vehículo que sube debe ceder el paso al que baja, pues este tiene menos capacidad de maniobra.' },
      { id:'P10', q:'¿Qué prioridad tiene el conductor en un carril de aceleración de autopista?', options:['Tiene prioridad sobre los que ya circulan por la autopista','Debe ceder el paso a los que circulan por la autopista','Tienen la misma preferencia','Depende de la velocidad de cada uno'], correct:1, explanation:'El carril de aceleración sirve para igualar velocidad con el tráfico de la autopista. El conductor que se incorpora debe ceder el paso.' },
      { id:'P11', q:'En una intersección con semáforo averiado, ¿qué norma aplica?', options:['Tiene prioridad el que lleva más prisa','Se aplica la norma de la derecha','El vehículo mayor tiene prioridad','Todos se detienen indefinidamente'], correct:1, explanation:'Ante un semáforo averiado, se aplican las normas generales de prioridad: la norma de la derecha y el sentido común.' },
      { id:'P12', q:'¿Tienen preferencia los peatones en un paso señalizado cuando están cruzando?', options:['Nunca, siempre ceden el paso','Siempre que estén cruzando o esperando para cruzar','Solo si el semáforo peatonal está en verde','Solo si el coche circula a menos de 30 km/h'], correct:1, explanation:'En los pasos de peatones señalizados, los peatones tienen preferencia tanto cuando cruzan como cuando esperan para hacerlo.' },
      { id:'P13', q:'¿Qué prioridad tienen los vehículos militares en convoy?', options:['Ninguna especial','Prioridad de paso si lo indica su señalización y vigilancia','Prioridad absoluta','Solo prioridad en carretera, no en ciudad'], correct:1, explanation:'Los convoyes militares debidamente señalizados tienen prioridad de paso. Debes respetar el convoy sin interrumpirlo.' },
      { id:'P14', q:'¿Quién tiene preferencia cuando dos vehículos convergen al mismo carril?', options:['El más grande','El que va más rápido','El que se encuentra más a la derecha','El que lleva más tiempo circulando'], correct:2, explanation:'Cuando dos vehículos convergen hacia el mismo espacio, tiene prioridad el que circula más a la derecha.' },
      { id:'P15', q:'¿Qué prioridad tienen los autobuses de línea al reincorporarse al tráfico en zona urbana?', options:['La misma que cualquier otro vehículo','Prioridad sobre los vehículos del carril adyacente si señalizan correctamente','Prioridad absoluta sobre todos','No tienen ninguna prioridad especial'], correct:1, explanation:'Los autobuses de línea tienen prioridad al reincorporarse desde una parada en zona urbana, siempre que señalicen la maniobra.' },
    ],
    'velocidad': [
      { id:'V01', q:'¿Cuál es la velocidad máxima en autopista para turismos?', options:['100 km/h','110 km/h','120 km/h','130 km/h'], correct:2, explanation:'La velocidad máxima en autopistas y autovías para turismos es de 120 km/h, salvo señalización específica.' },
      { id:'V02', q:'¿Cuál es la velocidad máxima en zona urbana con carácter general?', options:['30 km/h','40 km/h','50 km/h','60 km/h'], correct:2, explanation:'El límite general en zonas urbanas es 50 km/h. Puede haber zonas con 30 km/h (zonas 30) o 20 km/h (zonas de coexistencia).' },
      { id:'V03', q:'¿Cuál es la velocidad máxima en carretera convencional para turismos?', options:['80 km/h','90 km/h','100 km/h','110 km/h'], correct:1, explanation:'En carreteras convencionales (sin separación física entre sentidos), la velocidad máxima para turismos es de 90 km/h.' },
      { id:'V04', q:'¿Cuál es la velocidad máxima en vías de doble calzada que no son autopista?', options:['90 km/h','100 km/h','110 km/h','120 km/h'], correct:1, explanation:'En vías de doble calzada o con separador central sin categoría de autopista o autovía, el límite para turismos es 100 km/h.' },
      { id:'V05', q:'¿Cuál es la velocidad mínima en autopista si el máximo es 120 km/h?', options:['40 km/h','50 km/h','60 km/h','80 km/h'], correct:2, explanation:'La velocidad mínima en autopistas es la mitad de la velocidad máxima permitida. Con límite 120 km/h, el mínimo es 60 km/h.' },
      { id:'V06', q:'¿A qué distancia mínima debes circular respecto al vehículo de delante a 120 km/h?', options:['50 metros','75 metros','100 metros','120 metros'], correct:2, explanation:'A 120 km/h se requieren al menos 100 metros de distancia de seguridad (equivale a unos 3 segundos).' },
      { id:'V07', q:'¿Está permitido superar el límite de velocidad para adelantar?', options:['Sí, hasta un 20% más','Sí, hasta 30 km/h más en autopista','No, nunca está permitido superar el límite','Sí, si la maniobra es rápida'], correct:2, explanation:'Nunca está permitido superar el límite de velocidad señalizado, ni siquiera durante un adelantamiento.' },
      { id:'V08', q:'¿Qué es la distancia de seguridad?', options:['El espacio mínimo entre vehículos en sentido contrario','El espacio libre que debe mantenerse con el vehículo de delante para frenar si para bruscamente','La distancia mínima al arcén','El margen lateral con los ciclistas'], correct:1, explanation:'La distancia de seguridad es el espacio entre tu vehículo y el de delante para poder frenar con seguridad si el otro para bruscamente.' },
      { id:'V09', q:'¿Cuál es el límite de velocidad en zonas de coexistencia peatonal?', options:['10 km/h','20 km/h','30 km/h','50 km/h'], correct:1, explanation:'En zonas de coexistencia (donde peatones y vehículos comparten el espacio), el límite de velocidad es de 20 km/h.' },
      { id:'V10', q:'¿Qué relación tiene la velocidad con la distancia de frenado?', options:['Es proporcional: al doble de velocidad, el doble de distancia','Aumenta al cuadrado: al doble de velocidad, cuatro veces más distancia de frenado','No hay relación directa','La distancia de frenado no varía con la velocidad'], correct:1, explanation:'La distancia de frenado crece con el cuadrado de la velocidad. Si duplicas la velocidad, necesitas cuatro veces más distancia para detenerte.' },
      { id:'V11', q:'¿Qué efecto tiene el viento lateral fuerte sobre el vehículo a alta velocidad?', options:['Ninguno en vehículos modernos','Puede desestabilizarlo, especialmente a vehículos altos y ligeros','Solo afecta a las motos','Mejora la estabilidad por el efecto aerodinámico'], correct:1, explanation:'El viento lateral fuerte puede desestabilizar el vehículo, sobre todo en puentes, zonas de sombra y en vehículos altos.' },
      { id:'V12', q:'Con lluvia intensa en autopista, ¿cómo debes adaptar la velocidad?', options:['120 km/h (igual que siempre)','100 km/h como máximo recomendado','90 km/h obligatoriamente','La que las condiciones permitan con seguridad, siendo la visibilidad el factor clave'], correct:3, explanation:'Con lluvia o mal tiempo debes adaptar la velocidad a las condiciones. Circular a 120 km/h con lluvia intensa puede ser imprudente.' },
      { id:'V13', q:'¿A qué velocidad máxima se aplica en un área escolar durante el horario escolar?', options:['50 km/h','30 km/h','La señalizada específicamente para la zona','20 km/h'], correct:2, explanation:'En áreas escolares se instalan señales de velocidad específicas que deben respetarse especialmente en los horarios de entrada y salida.' },
      { id:'V14', q:'¿Cuándo puede circular a 90 km/h en una vía urbana?', options:['Cuando no haya peatones','Nunca, el máximo urbano es 50 km/h salvo señalización específica','De noche si la vía está vacía','Si la calzada tiene 4 carriles'], correct:1, explanation:'El límite general en zona urbana es 50 km/h. Solo si hay una señal específica que autorice más velocidad se puede circular a más.' },
      { id:'V15', q:'¿Cuántos puntos se pierden por superar el límite en más de 50 km/h?', options:['2 puntos','4 puntos','6 puntos','Todo el saldo'], correct:2, explanation:'Superar el límite de velocidad en más de 50 km/h supone la pérdida de 6 puntos del carnet de conducir.' },
      { id:'V16', q:'¿Qué es el acuaplaning (aquaplaning)?', options:['Un derrape por exceso de velocidad en seco','Las ruedas pierden contacto con el suelo al flotar sobre agua, perdiendo dirección y frenado','Solo afecta a los frenos, no a la dirección','Fenómeno que solo ocurre a más de 150 km/h'], correct:1, explanation:'El acuaplaning ocurre cuando el agua no puede evacuarse bajo los neumáticos y las ruedas flotan. Se pierde tracción, frenado y dirección.' },
      { id:'V17', q:'¿Cuál es la distancia de seguridad en ciudad a 50 km/h (regla de los 2 segundos)?', options:['Unos 14 metros','Unos 28 metros','Unos 50 metros','No hay distancia mínima en ciudad'], correct:1, explanation:'La regla de los 2 segundos da unos 28 metros a 50 km/h. Este es el espacio mínimo recomendado para frenar con seguridad.' },
      { id:'V18', q:'¿Qué ocurre con la distancia de frenado si el firme está mojado?', options:['No varía significativamente','Aumenta considerablemente respecto al firme seco','Disminuye porque los neumáticos se adhieren mejor','Solo afecta en curvas'], correct:1, explanation:'En firme mojado, la distancia de frenado puede duplicarse o incluso triplicarse respecto al firme seco.' },
      { id:'V19', q:'¿Cuándo se aplica el límite de 30 km/h en carretera?', options:['Siempre','Nunca en carretera, solo en ciudad','Cuando hay señal específica de 30 km/h o en zonas de obras señalizadas','Cuando hay viento fuerte'], correct:2, explanation:'En carretera puede aplicarse el límite de 30 km/h mediante señales temporales (obras, condiciones especiales) o señales fijas en tramos específicos.' },
      { id:'V20', q:'¿Cuál es el límite para turismos en una autopista de peaje en condiciones normales?', options:['100 km/h','110 km/h','120 km/h','El que marque el GPS'], correct:2, explanation:'Las autopistas de peaje tienen el mismo límite general para turismos: 120 km/h, salvo señalización diferente en tramos concretos.' },
    ],
    'adelantamiento': [
      { id:'A01', q:'¿Cuándo está prohibido adelantar en un paso de peatones?', options:['Solo si hay peatones cruzando','Siempre, en cualquier circunstancia','Solo de noche','Solo si el paso tiene semáforo'], correct:1, explanation:'Está absolutamente prohibido adelantar en los pasos de peatones y en sus inmediaciones, con o sin peatones.' },
      { id:'A02', q:'¿Qué debes hacer antes de iniciar un adelantamiento?', options:['Tocar el claxon y acelerar','Comprobar que la vía está libre, señalizar, y que hay espacio y visibilidad suficientes','Avisar al vehículo de atrás con los frenos','Encender las luces de cruce'], correct:1, explanation:'Antes de adelantar: comprueba que la vía está libre, señaliza con el intermitente izquierdo, y asegúrate de tener visibilidad y espacio.' },
      { id:'A03', q:'¿Está permitido adelantar en una intersección sin señalizar?', options:['Sí, si hay visibilidad','No, está prohibido adelantar en intersecciones no señalizadas','Solo si es una vía prioritaria','Solo si la intersección es de poca importancia'], correct:1, explanation:'El adelantamiento está prohibido en intersecciones no señalizadas como prioritarias. La falta de visibilidad lo hace especialmente peligroso.' },
      { id:'A04', q:'¿Qué debe hacer el conductor que va a ser adelantado?', options:['Acelerar para que sea más rápido','Mantener su velocidad y posición, facilitando la maniobra','Reducir la velocidad drásticamente','Moverse hacia el centro de la calzada'], correct:1, explanation:'El vehículo que va a ser adelantado no debe obstaculizar la maniobra ni acelerar. Debe mantener su velocidad y posición.' },
      { id:'A05', q:'¿Cuándo está permitido adelantar por la derecha?', options:['Nunca','Cuando el vehículo de delante va a girar a la izquierda y hay espacio suficiente','En autopista si el de la izquierda no cede el paso','Siempre que haya prisa'], correct:1, explanation:'El adelantamiento por la derecha solo está permitido cuando el vehículo de delante señaliza que va a girar a la izquierda y hay espacio.' },
      { id:'A06', q:'Tras completar un adelantamiento, ¿qué debes hacer?', options:['Quedarte en el carril izquierdo por comodidad','Incorporarte al carril derecho señalizando y dejando espacio al adelantado','Frenar inmediatamente para dejar espacio','Apagar el intermitente antes de incorporarte'], correct:1, explanation:'Tras adelantar: señaliza con el intermitente derecho, vuelve al carril derecho dejando suficiente espacio al vehículo adelantado.' },
      { id:'A07', q:'¿Está permitido adelantar cuando hay niebla intensa?', options:['Sí, si las luces de niebla están encendidas','No, la falta de visibilidad lo hace extremadamente peligroso','Solo en autopista con arcén amplio','Sí, si se usa el claxon para avisar'], correct:1, explanation:'Con niebla intensa, la visibilidad reducida hace imposible asegurar que el adelantamiento sea seguro.' },
      { id:'A08', q:'¿A qué separación mínima debes adelantar a un ciclista pudiendo invadir el carril contrario?', options:['0,5 metros de separación','1 metro de separación','1,5 metros de separación','No se puede invadir el carril contrario en ningún caso'], correct:2, explanation:'Para respetar la separación lateral mínima de 1,5 metros con el ciclista, es legal invadir parcialmente el carril contrario con visibilidad suficiente.' },
      { id:'A09', q:'¿Está prohibido adelantar antes y dentro de los túneles?', options:['Solo dentro del túnel','En los tramos sin visibilidad suficiente antes y dentro del túnel','No hay restricciones especiales en túneles','Solo de noche'], correct:1, explanation:'En túneles y sus inmediaciones, la falta de visibilidad hace especialmente peligroso el adelantamiento. Se aplican las normas generales.' },
      { id:'A10', q:'¿Cuántos puntos se pierden por adelantar en una línea continua?', options:['2 puntos','4 puntos','6 puntos','Ninguno, solo hay multa'], correct:2, explanation:'Adelantar cruzando una línea continua supone la pérdida de 6 puntos del carnet de conducir, además de la multa económica.' },
      { id:'A11', q:'¿Está prohibido el adelantamiento en los cambios de rasante (cimas)?', options:['Sí, siempre en cualquier cima','No si la visibilidad es suficiente y no hay línea continua','Solo cuando la cima es pronunciada','Solo de noche'], correct:1, explanation:'No hay una prohibición genérica. Está prohibido cuando la visibilidad no es suficiente. Si hay buena visibilidad y sin línea continua puede ser legal.' },
      { id:'A12', q:'¿Qué indica una zona de adelantamiento prohibido señalizada?', options:['Solo es orientativa','Es obligatorio respetar la prohibición aunque haya buena visibilidad','Solo si hay señal en ambos sentidos','Solo aplica a camiones y autobuses'], correct:1, explanation:'Las zonas de adelantamiento prohibido (señales verticales + línea continua) son de obligatorio cumplimiento. La visibilidad no justifica saltárselas.' },
    ],
    'alcohol': [
      { id:'AL01', q:'¿Cuál es la tasa de alcoholemia permitida para conductores en general?', options:['0,25 mg/l en aire espirado','0,50 mg/l en aire espirado','0,30 mg/l en aire espirado','0,80 mg/l en aire espirado'], correct:0, explanation:'La tasa de alcoholemia permitida para conductores en general es de 0,25 mg/l en aire espirado (equivale a 0,5 g/l en sangre).' },
      { id:'AL02', q:'¿Cuál es la tasa para conductores noveles (menos de 2 años) y profesionales?', options:['0,25 mg/l','0,15 mg/l','0,10 mg/l','0,00 mg/l (cero)'], correct:1, explanation:'Los conductores noveles y los profesionales tienen un límite inferior: 0,15 mg/l en aire espirado (0,3 g/l en sangre).' },
      { id:'AL03', q:'¿Puede un conductor negarse a la prueba de alcoholemia?', options:['Sí, es un derecho del conductor','No, la negativa es delito castigado con pena de prisión','Sí, si ya realizó una prueba ese mismo día','Solo puede negarse si no ha bebido nada'], correct:1, explanation:'Negarse a las pruebas de detección de alcohol o drogas constituye un delito con pena de prisión de 6 meses a 1 año.' },
      { id:'AL04', q:'¿Cuántos puntos se pierden por conducir con tasa de alcohol superior a la permitida?', options:['2 puntos','4 puntos','6 puntos','Todos los puntos'], correct:2, explanation:'Conducir con tasa de alcohol superior a la permitida supone la pérdida de 6 puntos del carnet, además de la sanción económica.' },
      { id:'AL05', q:'¿Qué efecto tiene el alcohol sobre el tiempo de reacción?', options:['Lo mejora por el efecto estimulante','Lo aumenta, haciendo más lenta la respuesta ante peligros','No tiene ningún efecto','Solo afecta a la visión, no al tiempo de reacción'], correct:1, explanation:'El alcohol altera el sistema nervioso central, aumentando el tiempo de reacción. Un conductor con alcohol tarda más en detectar y reaccionar ante el peligro.' },
      { id:'AL06', q:'¿Qué elimina realmente el alcohol del organismo?', options:['Dos cafés fuertes','El tiempo es lo único que elimina el alcohol','Ducharse con agua fría','Hacer ejercicio intenso'], correct:1, explanation:'Solo el tiempo elimina el alcohol del organismo. El café, el agua, el ejercicio o la ducha no aceleran la eliminación.' },
      { id:'AL07', q:'¿Qué efecto tiene el alcohol sobre la visión del conductor?', options:['Mejora la visión nocturna','Reduce el campo visual y empeora la percepción de profundidad','No afecta la visión, solo los reflejos','Amplía el campo visual'], correct:1, explanation:'El alcohol reduce el campo visual (efecto túnel), empeora la percepción de profundidad y dificulta la adaptación a cambios de luz.' },
      { id:'AL08', q:'¿Puede realizarse una segunda prueba de alcoholemia si el conductor lo solicita?', options:['No, el resultado de la primera es definitivo','Sí, tiene derecho a una segunda prueba','Solo si el resultado supera el doble del límite','Sí, pero debe pagar el coste'], correct:1, explanation:'El conductor tiene derecho a solicitar una segunda prueba. En caso de discrepancia, se toma la más favorable para el conductor.' },
      { id:'AL09', q:'¿Qué influye en el nivel de alcohol en sangre tras beber?', options:['Solo la cantidad de alcohol consumida','El peso, el sexo, la alimentación, el tiempo y la cantidad de alcohol consumida','Solo el peso corporal','Solo si se ha comido antes o no'], correct:1, explanation:'El nivel de alcohol en sangre depende de: cantidad consumida, peso, sexo (las mujeres metabolizan más lentamente), alimentación y tiempo transcurrido.' },
      { id:'AL10', q:'¿Qué consecuencia tiene conducir bajo los efectos de drogas de tráfico?', options:['Es solo infracción leve si no hay accidente','Es delito, con pena de prisión y suspensión del permiso','Solo se pierde el carnet temporalmente','Solo hay multa económica'], correct:1, explanation:'Conducir bajo los efectos de drogas es un delito contra la seguridad vial, con pena de prisión de 3 a 6 meses y privación del permiso.' },
      { id:'AL11', q:'¿Qué efecto tienen los tranquilizantes y somníferos sobre la conducción?', options:['Ninguno a dosis normales','Pueden reducir los reflejos y causar somnolencia','Mejoran la concentración al reducir la ansiedad','Solo afectan si se mezclan con alcohol'], correct:1, explanation:'Los tranquilizantes, somníferos y muchos fármacos pueden afectar la conducción produciendo somnolencia y reduciendo los reflejos.' },
      { id:'AL12', q:'¿Qué debe hacer un conductor cuyos medicamentos pueden afectar a la conducción?', options:['Conducir igual, los medicamentos no afectan mucho','Consultar con el médico y abstenerse de conducir si hay riesgo','Conducir solo trayectos cortos','Aumentar la dosis de cafeína para compensar'], correct:1, explanation:'Si los medicamentos pueden afectar la conducción, debes consultar con tu médico y abstenerse de conducir durante ese tratamiento.' },
      { id:'AL13', q:'¿Cuándo puede someterse a un conductor a una prueba de detección de drogas?', options:['Solo si ha tenido un accidente','En cualquier momento, sin necesidad de sospecha','Solo si se aprecia comportamiento anormal','Solo con autorización judicial'], correct:1, explanation:'Los agentes pueden someter a cualquier conductor a pruebas de detección de alcohol o drogas en cualquier control, sin necesidad de sospecha previa.' },
      { id:'AL14', q:'La diferencia entre conducción bajo efectos del alcohol y tasas superiores a las permitidas es:', options:['No hay diferencia, ambas son la misma infracción','La primera puede ser delito penal; superar la tasa sin síntomas es infracción administrativa si no supera ciertos niveles','Solo la segunda es sancionable','La primera es siempre más grave'], correct:1, explanation:'Conducir con síntomas de embriaguez es delito penal. Superar la tasa permitida sin síntomas evidentes es infracción grave administrativa (también puede ser delito a tasas muy altas).' },
      { id:'AL15', q:'¿Qué factor NO ayuda a eliminar el alcohol del organismo más rápidamente?', options:['El tiempo transcurrido','El café o el azúcar','La actividad física intensa','Todos (b y c son incorrectos)'], correct:3, explanation:'Solo el tiempo elimina el alcohol. El café, el azúcar, el agua fría o el ejercicio NO aceleran la metabolización. Solo dan la falsa sensación de estar más despierto.' },
    ],
    'mecanica': [
      { id:'M01', q:'¿Qué debes hacer si se te revienta una rueda a alta velocidad?', options:['Frenar bruscamente y tirar del volante al lado contrario','Sujetar firmemente el volante, soltar el acelerador gradualmente y detenerse con suavidad','Acelerar para mantener el control','Cambiar de carril rápidamente'], correct:1, explanation:'Ante un reventón: sujeta el volante con firmeza, no frenes bruscamente, suelta el acelerador con suavidad, deja que el vehículo se frene progresivamente.' },
      { id:'M02', q:'¿Cuándo deben usarse las luces de emergencia (cuatro intermitentes)?', options:['Para aparcar en zona de carga','En situaciones de peligro, avería o emergencia que afecten al tráfico','Al entrar en un túnel','Para agradecer a otros conductores'], correct:1, explanation:'Las luces de emergencia se usan para señalizar una situación de peligro, avería o emergencia. No está justificado usarlas para aparcar ilegalmente.' },
      { id:'M03', q:'¿Qué indica el testigo de aceite encendido mientras se conduce?', options:['Que es hora de cambiar el aceite','Baja presión de aceite: debes detenerte inmediatamente','Que el nivel de aceite es óptimo','Que el motor está caliente'], correct:1, explanation:'El testigo rojo de aceite indica baja presión de lubricación. Es una emergencia: debes detener el vehículo porque el motor puede dañarse gravemente.' },
      { id:'M04', q:'¿Cuál es la función principal del ABS?', options:['Reducir el consumo de combustible','Evitar que las ruedas se bloqueen durante el frenado para mantener la dirección','Mantener el vehículo estable en curvas','Controlar la tracción en superficies resbaladizas'], correct:1, explanation:'El ABS (Antiblockiersystem) evita que las ruedas se bloqueen al frenar bruscamente, lo que permite al conductor seguir dirigiendo el vehículo mientras frena.' },
      { id:'M05', q:'¿Cómo se debe frenar con ABS en una emergencia?', options:['Con bombeos rápidos del pedal de freno','Pisando el freno a fondo y sin soltarlo mientras se dirige el vehículo','Frenando progresivamente para no activar el ABS','Usando solo el freno de mano'], correct:1, explanation:'Con ABS, en emergencia, debes pisar el freno a fondo y mantenerlo pisado. El sistema bombea automáticamente. Sigue dirigiendo el vehículo.' },
      { id:'M06', q:'¿Qué es el ESP o control de estabilidad?', options:['Un sistema que limita la velocidad automáticamente','Un sistema que detecta y corrige la inestabilidad aplicando frenos individualmente','El sistema de dirección asistida','El control de crucero adaptativo'], correct:1, explanation:'El ESP (Electronic Stability Program) detecta cuando el vehículo se desvía de la trayectoria deseada y aplica frenado en ruedas individuales para estabilizarlo.' },
      { id:'M07', q:'¿Qué indica el testigo de temperatura del motor?', options:['Que el motor ha alcanzado su temperatura óptima','Que el motor está sobrecalentando: debes parar con seguridad','Que la calefacción está encendida','Que el ventilador del radiador no funciona'], correct:1, explanation:'Si el testigo de temperatura está en rojo o la aguja en el máximo, el motor se sobrecalienta. Debes parar el vehículo y apagar el motor.' },
      { id:'M08', q:'¿Qué profundidad mínima del dibujo deben tener los neumáticos?', options:['1 mm','1,6 mm','3 mm','4 mm'], correct:1, explanation:'La profundidad mínima legal del dibujo de los neumáticos es de 1,6 mm. Por debajo, la capacidad de evacuación de agua y el agarre disminuyen peligrosamente.' },
      { id:'M09', q:'¿Cuál es la función del airbag?', options:['Sustituye al cinturón de seguridad','Complementa al cinturón de seguridad, amortiguando el impacto del cuerpo contra el habitáculo','Protege principalmente en impactos laterales','Funciona igual con o sin cinturón'], correct:1, explanation:'El airbag es un complemento del cinturón de seguridad, no un sustituto. Sin cinturón puede causar lesiones graves.' },
      { id:'M10', q:'¿Qué efecto tiene conducir con los neumáticos con poca presión?', options:['Mayor agarre y seguridad','Mayor consumo de combustible, desgaste irregular y riesgo de reventón','Mejor comportamiento en curva','Menor distancia de frenado'], correct:1, explanation:'Los neumáticos con presión insuficiente aumentan el consumo, se desgastan más rápido en los bordes y aumentan el riesgo de reventón.' },
      { id:'M11', q:'Si el vehículo derrapa en hielo, ¿qué debes hacer?', options:['Frenar bruscamente para recuperar el control','Girar el volante bruscamente al lado contrario al derrape','Soltar el acelerador suavemente y girar el volante en la dirección del derrape','Pisar el freno y el embrague a la vez'], correct:2, explanation:'En un derrape sobre hielo: suelta el acelerador con suavidad y gira el volante en la MISMA dirección del derrape. No frenes bruscamente.' },
      { id:'M12', q:'¿En qué situación debes activar el freno de mano (freno de estacionamiento)?', options:['Al parar en semáforo siempre','Al estacionar el vehículo y siempre que se deje sin conductor','Solo en pendientes pronunciadas','Solo cuando el freno de pie no funciona'], correct:1, explanation:'El freno de estacionamiento debe usarse siempre que dejes el vehículo aparcado o sin conductor, independientemente de si hay pendiente o no.' },
      { id:'M13', q:'¿Qué indica el símbolo de una batería en el cuadro de instrumentos?', options:['Que la batería está completamente cargada','Que el alternador no está cargando la batería correctamente','Que es hora de cambiar la batería','Que el vehículo está en modo eléctrico'], correct:1, explanation:'El testigo de batería indica que el circuito de carga no funciona correctamente, es decir, que el alternador no está cargando la batería.' },
      { id:'M14', q:'¿Qué debes comprobar antes de un viaje largo?', options:['Solo el nivel de combustible','Niveles de aceite, agua, líquido de frenos, presión de ruedas, luces y documentación','Solo las luces y los frenos','Solo la presión de las ruedas'], correct:1, explanation:'Antes de un viaje largo, revisa: niveles (aceite, refrigerante, limpiaparabrisas, frenos), presión y estado de neumáticos, luces, frenos, y documentación.' },
      { id:'M15', q:'¿Qué puede indicar la vibración en el volante al frenar?', options:['Es normal, indica que el ABS funciona','Los discos de freno pueden estar deformados (combados)','Indica que la presión de los neumáticos es baja','El aceite de la dirección está bajo'], correct:1, explanation:'La vibración en el volante al frenar suele indicar que los discos de freno están deformados (combados o ovalados), lo que requiere revisión mecánica.' },
      { id:'M16', q:'¿Qué indica un testigo de color naranja/ámbar en el cuadro de instrumentos?', options:['Emergencia: parar inmediatamente','Aviso o atención: algo requiere revisión próxima pero no urgente','Todo funciona correctamente','El motor está en temperatura óptima'], correct:1, explanation:'Los testigos ámbar/naranja son de AVISO: indican algo que revisar sin urgencia inmediata. Los rojos son de emergencia. Los verdes/azules son informativos.' },
      { id:'M17', q:'¿Cuándo es obligatorio llevar chaleco reflectante?', options:['No es obligatorio, solo recomendable','Es obligatorio y debe ponerse ANTES de salir del vehículo en caso de avería o accidente','Solo si se conduce de noche','Solo en autopistas y autovías'], correct:1, explanation:'Es obligatorio llevar al menos un chaleco reflectante. En caso de avería o accidente, debes ponértelo ANTES de salir del vehículo.' },
      { id:'M18', q:'¿Cuál es la presión correcta de los neumáticos?', options:['La misma en todas las ruedas: 2,0 bar siempre','La indicada por el fabricante del vehículo para cada situación de carga','Lo máximo posible para mayor seguridad','La mínima posible para mayor agarre'], correct:1, explanation:'La presión correcta es la especificada por el fabricante del vehículo (en el marco de la puerta o el manual). Varía según la carga del vehículo.' },
    ],
    'iluminacion': [
      { id:'I01', q:'¿Cuándo es obligatorio el uso de luces de cruce de día?', options:['Siempre, incluso de día en todas las vías','En túneles, bajo lluvia intensa, niebla o cuando la visibilidad sea reducida','Solo de noche','Solo en autopistas'], correct:1, explanation:'Las luces de cruce son obligatorias de noche, en túneles, y de día cuando las condiciones reducen la visibilidad (lluvia, niebla, nieve, etc.).' },
      { id:'I02', q:'¿Cuándo deben usarse las luces largas (de carretera)?', options:['Siempre en autopista de noche','En vías interurbanas cuando no deslumbren a otros vehículos','Solo en carreteras sin iluminación','Siempre por encima de 90 km/h'], correct:1, explanation:'Las luces largas se usan en vías interurbanas cuando no hay vehículos en sentido contrario ni delante. Al aproximarse a otro vehículo, hay que cambiar a cortas.' },
      { id:'I03', q:'¿A qué distancia debes cambiar las luces largas a cortas al encontrar un vehículo contrario?', options:['A 50 metros','A 150 metros','A 200 metros','A 400 metros'], correct:1, explanation:'Debes cambiar a luces cortas cuando el vehículo contrario esté a menos de 150 metros, para evitar deslumbrarlo.' },
      { id:'I04', q:'¿Para qué sirven las luces de niebla delanteras?', options:['Para aumentar la visibilidad en condiciones de niebla, lluvia intensa o nieve','Para señalizar emergencias','Para iluminar mejor de noche sin niebla','Son decorativas'], correct:0, explanation:'Las luces de niebla delanteras iluminan la calzada de forma rasante en condiciones de niebla, lluvia densa o nieve, donde las normales crean deslumbramiento.' },
      { id:'I05', q:'¿Cuándo deben usarse las luces de niebla traseras?', options:['Siempre de noche','Solo cuando la visibilidad sea inferior a 50 metros por niebla, lluvia o nieve intensa','En cualquier condición de lluvia','Nunca, son peligrosas para el de detrás'], correct:1, explanation:'Las luces de niebla traseras (rojas, muy intensas) solo deben usarse cuando la visibilidad sea inferior a 50 metros. Sin necesidad deslumbran.' },
      { id:'I06', q:'¿Qué luz usas para señalizar el vehículo estacionado en vía mal iluminada de noche?', options:['Luces de cruce (cortas)','Luces de posición (luces de estacionamiento)','Luces de niebla','Luces largas'], correct:1, explanation:'Al estacionar en vía poco iluminada de noche, debes dejar las luces de posición encendidas para que el vehículo sea visible.' },
      { id:'I07', q:'Si un vehículo contrario te deslumbra, ¿qué debes hacer?', options:['Encender también tus luces largas para avisar','Mirar hacia el borde derecho de la calzada y reducir velocidad','Cerrar los ojos brevemente y seguir','Frenar bruscamente y parar'], correct:1, explanation:'Al ser deslumbrado: mira hacia el borde derecho de la calzada (no a la fuente de luz), reduce la velocidad y no frenes bruscamente.' },
      { id:'I08', q:'¿Es obligatorio encender las luces al entrar en un túnel aunque sea de día?', options:['No, solo en túneles de más de 500 metros','Sí, siempre que se entre en un túnel con señal de encendido de luces','Solo si el túnel está oscuro','No, los vehículos modernos lo hacen automáticamente'], correct:1, explanation:'Al entrar en un túnel señalizado, es obligatorio encender las luces independientemente de la hora del día y la longitud del túnel.' },
      { id:'I09', q:'¿Qué indica el testigo de color naranja/ámbar en el cuadro de instrumentos?', options:['Emergencia: parar inmediatamente','Aviso o atención: algo requiere revisión próxima pero no urgente','Todo funciona correctamente','El motor está en temperatura óptima'], correct:1, explanation:'Los testigos ámbar/naranja son de AVISO. Los rojos son de emergencia (parar). Los verdes/azules son informativos.' },
      { id:'I10', q:'¿Cuál es la diferencia entre luces de posición y luces de cruce?', options:['No hay diferencia, son lo mismo','Las de posición son pequeñas para ser visto; las de cruce iluminan la calzada','Las de posición iluminan más','Las de cruce son solo para adelantar'], correct:1, explanation:'Las luces de posición (piloto) son de baja intensidad y solo hacen visible el vehículo. Las de cruce iluminan la calzada para que el conductor pueda ver.' },
      { id:'I11', q:'¿Para qué sirve el uso de luces de cruce durante el día en carretera?', options:['No tienen ninguna utilidad de día','Aumentan la visibilidad del vehículo para los demás usuarios','Reducen el consumo del motor','Activan el control de crucero'], correct:1, explanation:'Usar las luces de cruce de día mejora la visibilidad del vehículo ante otros conductores, peatones y ciclistas, reduciendo el riesgo de accidente.' },
      { id:'I12', q:'¿Cuándo se activan automáticamente las luces de marcha atrás?', options:['Solo de noche','Se activan automáticamente al meter la marcha atrás','El conductor las activa cuando necesita retroceder','Solo si hay obstáculos detrás'], correct:1, explanation:'Las luces de marcha atrás (blancas) se activan automáticamente al engancharse la marcha atrás. Indican a los demás que el vehículo va a retroceder.' },
    ],
    'medioambiente': [
      { id:'ME01', q:'¿Qué gas es el principal responsable del efecto invernadero emitido por los vehículos?', options:['Monóxido de carbono (CO)','Dióxido de carbono (CO₂)','Óxidos de nitrógeno (NOx)','Partículas finas (PM2.5)'], correct:1, explanation:'El CO₂ es el principal gas de efecto invernadero emitido por los vehículos. Aunque el CO es más tóxico, el CO₂ contribuye más al cambio climático en volumen.' },
      { id:'ME02', q:'¿Qué etiqueta ambiental corresponde a los vehículos eléctricos puros según la DGT?', options:['Etiqueta ECO','Etiqueta B','Etiqueta C','Etiqueta 0 emisiones'], correct:3, explanation:'Los vehículos 100% eléctricos y los de pila de combustible tienen la etiqueta "0 emisiones" (cero emisiones), la más favorable del sistema.' },
      { id:'ME03', q:'¿Qué acción reduce más el consumo de combustible en carretera?', options:['Llevar el vehículo recargado al máximo','Circular a velocidad constante y moderada con marchas largas','Climatización al máximo','Usar las luces largas permanentemente'], correct:1, explanation:'Circular a velocidad constante y moderada en marchas largas (sin revoluciones innecesarias) es la forma más eficiente de reducir el consumo.' },
      { id:'ME04', q:'¿Qué efecto tiene circular con las ventanillas abiertas a alta velocidad?', options:['Lo reduce porque enfría el motor','Lo aumenta por la mayor resistencia aerodinámica','No tiene efecto significativo','Solo afecta si todas las ventanillas están abiertas'], correct:1, explanation:'A alta velocidad, las ventanillas abiertas aumentan la resistencia aerodinámica y por tanto el consumo. A más de 80 km/h es más eficiente usar el climatizador.' },
      { id:'ME05', q:'¿Cuánto puede aumentar el consumo llevar la baca vacía montada?', options:['No aumenta el consumo','Hasta un 10-15% por la mayor resistencia aerodinámica','Solo 1-2%','Un 50% más'], correct:1, explanation:'Una baca o portaequipajes vacío aumenta la resistencia aerodinámica y puede incrementar el consumo hasta un 10-15%. Es recomendable retirarlo cuando no se use.' },
      { id:'ME06', q:'¿Cómo influye la presión de los neumáticos en el consumo?', options:['No influye en el consumo','Una presión baja aumenta el consumo; la presión correcta lo optimiza','Mayor presión, mayor consumo','Solo la presión trasera afecta al consumo'], correct:1, explanation:'Los neumáticos con baja presión tienen mayor resistencia al rodamiento, aumentando el consumo. La presión correcta puede ahorrar un 3-5%.' },
      { id:'ME07', q:'¿Qué son las zonas de bajas emisiones (ZBE)?', options:['Zonas donde la velocidad está limitada a 20 km/h','Áreas urbanas donde se restringe la circulación de vehículos más contaminantes','Zonas solo para vehículos eléctricos','Carreteras de peaje para vehículos grandes'], correct:1, explanation:'Las ZBE son áreas urbanas donde solo pueden circular vehículos con etiqueta ambiental favorable, limitando el acceso a los más contaminantes.' },
      { id:'ME08', q:'¿Qué significa la etiqueta ECO de la DGT?', options:['Vehículo 100% eléctrico','Vehículos híbridos enchufables, híbridos convencionales o de gas con muy bajas emisiones','Vehículos Euro 6 de gasolina','Todos los vehículos fabricados después de 2015'], correct:1, explanation:'La etiqueta ECO identifica vehículos híbridos enchufables con autonomía >40 km, vehículos de gas (GLP, GNC) y de hidrógeno, con menores emisiones que los convencionales.' },
      { id:'ME09', q:'¿Cuándo es recomendable anticiparse a las situaciones de tráfico?', options:['Solo en autopista','Siempre: la anticipación evita aceleraciones y frenadas bruscas que consumen más','Solo en ciudad','Solo si el vehículo tiene control de crucero'], correct:1, explanation:'La conducción anticipada (levantar el pie del acelerador antes de frenar, mantener distancias) reduce aceleraciones y frenadas bruscas, ahorrando combustible.' },
      { id:'ME10', q:'¿Cuándo debe apagarse el motor para reducir emisiones en ciudad?', options:['Nunca, apagarle y arrancarle consume más','En paradas previsibles de más de 60 segundos','Solo si la parada es de más de 5 minutos','Solo en zonas de bajas emisiones señalizadas'], correct:1, explanation:'Apagar el motor en paradas de más de 60 segundos ahorra combustible y reduce emisiones. Los vehículos modernos con Start&Stop lo hacen automáticamente.' },
    ],
    'accidentes': [
      { id:'AC01', q:'¿Cuál es el orden correcto del protocolo PAS ante un accidente?', options:['Socorrer, Proteger, Avisar','Proteger, Avisar, Socorrer','Avisar, Socorrer, Proteger','Proteger, Socorrer, Avisar'], correct:1, explanation:'El protocolo PAS es: 1) PROTEGER la zona (evitar nuevos accidentes), 2) AVISAR a los servicios de emergencia (112), 3) SOCORRER a los heridos.' },
      { id:'AC02', q:'¿A qué número se llama en caso de accidente con heridos en España?', options:['091 (Policía)','112 (Emergencias europeo)','061 (Urgencias médicas)','080 (Bomberos)'], correct:1, explanation:'El 112 es el número único de emergencias europeo. Funciona desde cualquier teléfono (incluso sin cobertura propia o batería) y conecta con todos los servicios.' },
      { id:'AC03', q:'¿Cuándo debes mover a un herido en un accidente?', options:['Siempre para ponerlo más cómodo','Nunca, excepto si hay riesgo inmediato de incendio o hundimiento','Siempre si está inconsciente','Solo si el herido lo pide'], correct:1, explanation:'No debes mover a un herido a menos que exista un peligro inmediato (fuego, hundimiento). Moverlo incorrectamente puede agravar lesiones de columna.' },
      { id:'AC04', q:'¿Qué es la posición lateral de seguridad (PLS)?', options:['Colocar al herido boca arriba con piernas elevadas','Colocar al herido de lado para evitar que se ahogue con vómitos si respira','Sentarlo apoyado contra la rueda del coche','Colocar al herido boca abajo'], correct:1, explanation:'La PLS coloca al herido inconsciente (pero que respira) de lado, con la boca apuntando hacia abajo, para evitar que se atragante si vomita.' },
      { id:'AC05', q:'¿Cuántas compresiones por minuto se realizan en el masaje cardíaco (RCP)?', options:['30 por minuto','60 por minuto','100-120 por minuto','150 por minuto'], correct:2, explanation:'Las compresiones torácicas en la RCP deben realizarse a 100-120 por minuto, con una profundidad de 5-6 cm. Se alternan 30 compresiones con 2 ventilaciones.' },
      { id:'AC06', q:'Si hay una hemorragia externa intensa, ¿qué debes hacer?', options:['Aplicar torniquete siempre en primer lugar','Presionar directamente sobre la herida con un trapo limpio o apósito','Elevar la extremidad pero no presionar','Limpiar la herida con agua antes de presionar'], correct:1, explanation:'Para controlar una hemorragia externa, la medida más efectiva y segura es la presión directa sobre la herida. El torniquete solo se usa como último recurso.' },
      { id:'AC07', q:'¿Es obligatorio detenerse si eres testigo de un accidente con heridos?', options:['No, solo si estás implicado','Sí, tienes obligación de prestar auxilio si no supone riesgo para ti','Solo si hay señal de obligatoriedad','Solo si eres el primer vehículo en llegar'], correct:1, explanation:'La legislación española obliga a prestar socorro a los accidentados cuando no suponga peligro para el propio conductor. Omitir este socorro es un delito.' },
      { id:'AC08', q:'¿Cuándo se debe retirar el casco a un motorista accidentado?', options:['Siempre, es lo primero que hay que hacer','Nunca, el personal sanitario es quien debe retirarlo salvo riesgo vital','Solo si el casco está dañado','Solo si el motorista lo solicita'], correct:1, explanation:'No debes retirar el casco a menos que sea imprescindible para mantener la vida. La retirada incorrecta puede agravar lesiones cervicales.' },
      { id:'AC09', q:'En caso de incendio del vehículo, ¿qué debes hacer?', options:['Intentar apagarlo antes de salir','Detener el vehículo, apagar el motor, salir rápido y alejarse al menos 50 metros','Abrir el capó para apagar con agua','Permanecer dentro del vehículo'], correct:1, explanation:'En caso de incendio: para el vehículo, apaga el motor, sal inmediatamente, aléjate al menos 50 metros y llama al 112. Nunca abras el capó si hay fuego bajo él.' },
      { id:'AC10', q:'¿Qué información básica debes dar al llamar al 112?', options:['Solo el número de heridos','Localización exacta, tipo de accidente, número aproximado de heridos y tu nombre','Solo la localización','El número de matrícula de los vehículos'], correct:1, explanation:'Al llamar al 112 indica: 1) Localización exacta, 2) Qué ha ocurrido, 3) Número y estado de los heridos, 4) Tu nombre y teléfono.' },
      { id:'AC11', q:'¿Es obligatorio dar datos del seguro al otro conductor en un accidente con daños materiales?', options:['No, si no hay heridos puedes marcharte','Sí, es obligatorio identificarse e intercambiar datos del seguro','Solo si el otro conductor lo pide','Solo si los daños superan los 1.000€'], correct:1, explanation:'En cualquier accidente con daños, los conductores implicados DEBEN detenerse, identificarse y facilitar los datos del seguro. Fugarse es un delito.' },
      { id:'AC12', q:'¿Cómo se llama la maniobra básica de reanimación cardiopulmonar?', options:['OVACE','RCP (Reanimación Cardiopulmonar)','PLS (Posición Lateral de Seguridad)','FAST (Face, Arms, Speech, Time)'], correct:1, explanation:'La RCP consiste en la combinación de compresiones torácicas y ventilaciones de rescate para mantener la circulación y oxigenación cuando el corazón se ha parado.' },
    ],
  },
  // El resto de permisos tendrán contenido próximamente
};

// =================== FUNCIONES DE ACCESO ===================

const QUESTIONS_PER_TEST = 30;

function getTestQuestions(permitId, temaId, testNum) {
  const bank  = (QBANK[permitId] && QBANK[permitId][temaId]) || [];
  const start = (testNum - 1) * QUESTIONS_PER_TEST;
  const end   = testNum * QUESTIONS_PER_TEST;
  const real  = bank.slice(start, end);

  const result = [...real];
  // Pad with placeholders if needed
  for (let i = real.length; i < QUESTIONS_PER_TEST; i++) {
    result.push({
      id:          `PH_${testNum}_${i + 1}`,
      q:           `Pregunta ${i + 1} — Contenido oficial pendiente de importar`,
      options:     ['Opción A', 'Opción B', 'Opción C', 'Opción D'],
      correct:     0,
      explanation: 'Esta pregunta será reemplazada por contenido oficial próximamente.',
      image:       null,
      isPlaceholder: true,
    });
  }
  return result;
}

function getTestStatus(permitId, temaId, testNum) {
  const bank  = (QBANK[permitId] && QBANK[permitId][temaId]) || [];
  const start = (testNum - 1) * QUESTIONS_PER_TEST;
  if (bank.length > start) {
    const real = bank.slice(start, testNum * QUESTIONS_PER_TEST).length;
    return real >= QUESTIONS_PER_TEST ? 'full' : 'partial';
  }
  return 'empty';
}

function getPermit(id)  { return PERMITS.find(p => p.id === id) || null; }
function getTopics(pid) { return PERMIT_TOPICS[pid] || []; }
function getTopic(pid, tid) { return getTopics(pid).find(t => t.id === tid) || null; }
